name: reviewdog
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'
jobs:
  lint:
    name: runner / lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: github-check
          level: warning
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          level: warning
